project:
  type: book
  output-dir: docs
  render:
    - "!tmp/"
    - "!LICENSE.md"

book:
  title: "Vademecum monitoraggio civico"
  author: "ASud"
  date: "22/11/2022"
  page-navigation: true
  chapters:
    - index.qmd
    - part: cultura-dato/come.qmd
      chapters:
        - cultura-dato/descrivere.qmd
        - cultura-dato/licenza.qmd
        - cultura-dato/formati.qmd
        - cultura-dato/forma.qmd
        - cultura-dato/scaricabili.qmd
    - part: "Strumenti"
      chapters:
        - cultura-dato/creare-csv.qmd
        - cultura-dato/accesso.qmd
        - cultura-dato/raccolta.qmd

format:
  html:
    theme: cosmo
    lang: it
    toc-depth: 4
