project:
  type: book
  output-dir: docs
  resources: CNAME
  render:
    - "!tmp/"
    - "!LICENSE.md"

book:
  title: "Vademecum monitoraggio ambientale"
  page-navigation: true

  sidebar:
    style: docked
    background: light
    search: true
    collapse-level: 1

  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        file: index.qmd
      - text: "Crediti"
        file: crediti.qmd

  chapters:
    - index.qmd
    - text: "Partecipazione civica e politiche pubbliche"
      file: politiche-pubbliche/index.qmd
    - part: "I Monitoraggi ambientali partecipati"
      chapters:
        - file: monitoraggi-ambientali-partecipati/citizen-science.qmd
          text: "Cos’è la Citizen science"
        - file: monitoraggi-ambientali-partecipati/perche-avviarli.qmd
          text: "Perché avviarli"
    - part: monitoraggio-acque/index.qmd
      chapters:
        - file: monitoraggio-acque/torbidita.qmd
        - file: monitoraggio-acque/ph.qmd
        - file: monitoraggio-acque/conducibilita.qmd
          text: "Conducibilità elettrica"
        - file: monitoraggio-acque/nitrati.qmd
        - file: monitoraggio-acque/fosfati.qmd
        - file: monitoraggio-acque/escherichia-coli.qmd
        - file: monitoraggio-acque/ammoniaca.qmd
    - part: monitoraggi-ambientali-estremi/index.qmd
      chapters:
        - file: monitoraggi-ambientali-estremi/basilicata.qmd
          text: "Basilicata"
        - file: monitoraggi-ambientali-estremi/fukushima.qmd
          text: "Fukushima"
        - file: monitoraggi-ambientali-estremi/ecuador.qmd
          text: "Ecuador"
        - file: monitoraggi-ambientali-estremi/altri-casi.qmd
          text: "Altri casi"
    - part: cultura-dato/come.qmd
      chapters:
        - cultura-dato/descrivere.qmd
        - cultura-dato/licenza.qmd
        - cultura-dato/formati.qmd
        - cultura-dato/forma.qmd
        - cultura-dato/scaricabili.qmd
    - part: "Strumenti"
      chapters:
        - cultura-dato/creare-csv.qmd
        - cultura-dato/accesso.qmd
        - cultura-dato/raccolta.qmd

  page-footer:
    left: |
      Un progetto di [ASud](https://asud.net)
    right: |
      Licenza [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.it)

format:
  html:
    theme: cosmo
    lang: it
    toc-depth: 4
    number-sections: false
    link-external-newwindow: true
    link-external-filter: '.*vademecum\.asud\.net\.*'
    email-obfuscation: javascript

execute:
  freeze: auto
