---
title: "Perché avviare percorsi di citizen science sul territorio"
toc: false
---

Le ragioni che ci hanno spinto ad avviare le analisi sul Tevere e successivamente sull’Aniene sono state diverse. Alla fine del 2020 come associazione ci siamo interrogati su quali fossero le principali problematiche ambientali a Roma. Dopo aver svolto un’indagine prendendo come riferimento i dati comunali, abbiamo deciso di svolgere un focus group nella nostra sede in cui abbiamo invitato diverse realtà che da anni si occupano di questioni ambientali in città e in parte anche in provincia, tra cui il comitato che si batte per la tutela del parco della Snia, il comitato No Tmb Salario, il Coordinamento romano acqua pubblica, l’associazione Insieme per l’Aniene.

L’esito della discussione è stata che la maggior parte delle realtà attive si trovava in una situazione di conflittualità con le istituzioni e, nella maggior parte dei casi, **i dati e le informazioni in generale fornite dal pubblico erano carenti**: il comitato No Tmb Salario lamentava la mancanza di un progetto chiaro di riqualificazione dell’area del Tmb Salario dopo l’incendio che lo aveva colpito, i comitati di Centocelle lamentavano una lentezza da parte delle istituzioni per l’avvio della bonifica di un’area problematica come quella del parco in cui erano stati rinvenuti rifiuti, il coordinamento romano acqua pubblica in accordo anche con Insieme per l’Aniene ha posto invece un tema rispetto ai dati della qualità dell’acqua e della sua quantità. **Sebbene infatti le perdite idriche delle condotte romane rasenta il 45%, Acea anziché puntare in maniera radicale sul recupero delle reti sta immaginando nuove fonti di approvvigionamento per l’acqua.** Dopo la problematica situazione di Bracciano (nel 2017 a seguito della crisi idrica si è prelevata l’acqua del lago causando un grave problema all’ecosistema lago) Acea ha scelto di investire nella realizzazione di un potabilizzatore. L’acqua del Tevere dovrebbe dunque essere potabilizzata per poi scorrere nelle reti idriche romane.

Tale situazione, secondo i comitati, è discutibile da due punti di vista: sul piano teorico perché prima di realizzare una nuova opera occorrerebb**e fare il possibile per ridurre le perdite idriche della rete** (risparmio). In secondo luogo perché **l’acqua del Tevere non è di buona qualità**, così come dimostrato dai risultati Arpa e dai monitoraggi partecipati svolti da A Sud, sebbene si preveda di trattarla prima dell’immissione in rete.

Tale affermazione è confermata dalle diverse **morie di pesci** che ci sono state nel corso degli ultimi due anni durante l’estate proprio lungo il corso del fiume.

Per tali ragioni si è scelto di avviare un percorso di monitoraggio sul Tevere al fine di monitorarne la qualità dell’acqua in otto diversi punti del tratto urbano.

Ragioni simili riguardano i territori di Colleferro e di Valle Galeria. In questi due casi, i percorsi attuati sono stati i monitoraggi sulla qualità dell’aria. In particolare a Colleferro si è voluto comprendere in che maniera il complesso urbano risenti ancora oggi della presenza industriale (cementificio) o del traffico urbano legato allo sviluppo del polo logistico Amazon nel territorio. In Valle Galeria invece, dove il percorso di monitoraggio è stato appena avviato, si è scelto di analizzare uno dei punti più critici della periferia romana in cui sono visibili i segni della presenza dell’ex discarica, del traffico legato alla presenza industriale, nonché le cave. Infine nel caso di Roma est, si è scelto di monitorare la presenza di particolato nell’aria proprio per comprendere quale sia la qualità dell’aria in prossimità delle scuole.
