---
title: "Accedere alle informazioni"
---

## Introduzione

Le Pubbliche Amministrazioni hanno degli **obblighi** di **pubblicità**, **trasparenza** e **diffusione** di **informazioni**.<br>
La norma di riferimento è il [Decreto Legislativo numero 33 del 14 marzo 2013](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2013-03-14;33!vig), denominato "*Riordino della disciplina riguardante il diritto di accesso civico e gli obblighi di pubblicità, trasparenza e diffusione di informazioni da parte delle pubbliche amministrazioni*".

::: {.callout-tip}
## Cosa è la Trasparenza per il decreto 33

La trasparenza è intesa come **accessibilità totale** (dei dati e documenti detenuti dalle pubbliche amministrazioni), allo scopo di tutelare i diritti dei cittadini, promuovere la partecipazione degli interessati all'attivita' amministrativ e favorire forme diffuse di controllo sul perseguimento delle funzioni istituzionali e sull'utilizzo delle risorse pubbliche.
:::


## Come si realizza l'accessibilità alle informazioni

L'accesssibilità totale a dati e documenti della PA, citata poco sopra, si realizza con tre tipi di accesso:

- [**Accesso documentale**](#accesso-documentale);
- [**Accesso civico semplice**](#accesso-civico-semplice);
- [**Accesso civico generalizzato**](#accesso-civico-generalizzato).

### Accesso documentale

L'"**Accesso documentale**" nasce con l'entrata in vigore della [legge 241 del 1990](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:1990-08-07;241!vig). Disciplina l'**accesso** ai **documenti amministrativi** dei **soggetti cosidetti interessati**, ossia tutti coloro che abbiano un interesse diretto, concreto e attuale, corrispondente ad una situazione giuridicamente tutelata e collegata al documento al quale è richiesto l'accesso.

### Accesso civico semplice

L'"**Accesso civico semplice**", diversamente dall'Accesso documentale, è un diritto che incontra limiti solo negli obblighi di pubblicazione definiti dal suddetto [d.lgs. 33/2013](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2013-03-14;33!vig).<br>
Il decreto infatti fissa l'elenco dei documenti che le PA devono pubblicare in una sezione del loro sito internet, denominata "Amministrazione Trasparente".<br>
In riferiento a questo afferma che «chiunque ha **diritto** di **richiedere documenti**, **dati** o **informazioni** che le **amministrazioni hanno l'obbligo di pubblicare nella sezione "Amministrazione trasparente"** dei propri siti istituzionali, nei casi in cui gli stessi non siano stati pubblicati».

I documenti che le PA devono pubblicare sono quelli compresi nel Capo II e Capo III del d.lgs. 33/2013 (articoli da 12 a 42). Il 40 è intitolato "[**Pubblicazione e accesso alle informazioni ambientali**](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2013-03-14;33!vig~art40)" e prevede che le amministrazioni pubblichino sui propri siti istituzionali le informazioni ambientali di cui all'articolo 2, comma 1, lettera a), del [decreto legislativo 19 agosto 2005, n. 195](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2005-08-19;195~art2-com1-leta).

### Accesso civico generalizzato

Quest'ultimo tipo di accesso si realizza con il [Decreto Legistativo numero 97 del 25 maggio 2016](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2016-05-25;97!vig).<br>
È una piccola rivoluzione sul diritto di accesso, che **allarga** in **modo** appunto **generalizzato il diritto di accesso ai documenti e alle informazioni detenute dalle pubbliche amministrazioni**.<br>
All'articolo 5, comma 2 recita:

> Allo scopo di favorire forme diffuse di controllo…e di promuovere la partecipazione al dibattito pubblico, chiunque ha diritto di accedere ai dati e ai documenti detenuti dalle pubbliche amministrazioni ulteriori rispetto a quelli oggetto di pubblicazione…

Si devono **identificare** i **dati**, le **informazioni** o i **documenti desiderati**,**senza che sia necessario definire una motivazione**.<br>
Questo diritto di accesso è il cosiddetto **FOIA** (Freedom of Information Act), che ha alcune eccezioni dettagliate nell'[articolo 6](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2016-05-25;97!vig~art6).<br>
Queste eccezioni però sono nella gran parte dei casi non correlabili ai dati ambienatli (segreto di stato, privacy delle persone, questioni militari, stabilità finanziaria, ecc.).

A proposito di possibili **limitazioni** nelle richieste di accesso generalizzato, è bene fare riferimento alle [**Linee Guida 1309/216**](https://www.anticorruzione.it/portal/rest/jcr/repository/collaboration/Digital%20Assets/anacdocs/Attivita/Atti/determinazioni/2016/1309/del.1309.2016.det.LNfoia.pdf) dell'Autorità Nazionale Anti Corruzione (ANAC):

1. **non è ammissibile** una **richiesta** meramente **esplorativa**, volta semplicemente a «scoprire» quali informazioni l’amministrazione detiene. Le richieste non devono essere generiche, ma consentire l'individuazione del dato, informazione o documento con riferimento, almeno, alla loro natura e al loro oggetto;
2. **non è possibile richiedere un numero manifestamente irragionevole di documenti**, tale da imporre un carico di lavoro tale da paralizzare, in modo sostanziale, il buon funzionamento dell’amministrazione;
3. per informazioni si devono considerare le rielaborazione di **dati già detenuti dalle amministrazioni**. L'amministrazione non è tenuta a formare o raccogliere o altrimenti procurarsi informazioni che non siano già in suo possesso.

## Fare una richiesta di accesso

Prima di procedere si consiglia di:

- verificare qual è l'amministrazione che dovrebbe detenere i documenti/dati che interessano;
- consultare il sito dell'amministrazione per verificare che non siano già pubblicati;
- se non sono presenti, aprire sul sito web di quella amministrazione, la sezione “amministrazione > altri contenuti > accesso civico” e verificare l'esistenza di un apposito modello predisposto dall'amministrazione per fare queste richieste (si può anche presentare un'istanza senza ricorrere al modulo che propone l'amministrazione).

La richiesta potrà essere fatta:

1. all'ufficio che detiene i dati, le informazioni o i documenti;
2. all'Ufficio relazioni con il pubblico (URP);
3. ad altro ufficio indicato dall'amministrazione nella sezione "Amministrazione trasparente" del sito istituzionale;
4. al responsabile della prevenzione della corruzione e della trasparenza, ove l'istanza abbia a oggetto dati, informazioni o documenti oggetto di pubblicazione obbligatoria ai sensi del d.lgs. 33/2013 (quindi in caso di [accesso civico semplice](#accesso-civico-semplice)).

La richiesta dovrà contenere:

- le generalità della/lo singola/o cittadina/o o del/lla legale rappresentante ad esempio di un'associazione;
- l'indicazione (il più precisa possibile) dei dati/documenti richiesti;
- l'indirizzo e le modalità con cui si vogliono ricevere i documenti/dat.

Può essere inviata con modalità tradizionali (raccomandata, lettera), oppure via mail/pec.

## Il procedimento di gestione di una richiesta di accesso civico generalizzato

La Pubblica Amministrazione che riceve la richiesta smista la domanda al soggetto compentente a rispondere. Se non comprende la richiesta ricevuta, chiederà chiarimenti al mittente.<br>
Se ci sono controinteressati, la PA li avvisa della richiesta e chiede loro se si oppongono (e per quali motivi); in questo caso, il termine entro cui deve rispondere si sospende per 10 giorni.
Successivament **emette provvedimento motivato** (sia di accoglimento sia di rigetto), **entro 30 giorni dalla ricezione della richiesta** e - se ha avuto costi vivi sostenuti per la riproduzione su supporti materiali (CD, DVD, stampa, ecc.) - richiede il rimborso dei costi sostenuti.

Se non risponde entro il termine di 30 giorni, **la mancata risposta equivale al diniego**.

### Cosa fare in caso di diniego o mancata risposta

In caso di diniego parziale o totale, ovvero di mancata risposta entro il termine dei 30 giorni, è possibile fare **richiesta** di riesame al **Responsabile della Prevenzione della Corruzione e della Trasparenza**, che deve decidere **entro 20 giorni** dalla richiesta di riesame.<br>
Se l'accesso alle informazioni è stato negato o differito a tutela degli interessi relativi alla protezione dei dati personali, il suddetto responsabile sente il Garante per la protezione dei dati personali, il quale si dovrà pronunciare entro il termine di dieci giorni dalla richiesta.

Nel caso di ulteriore decisione avversa da parte del Responsabile della trasparenza, è possibile procedere tramite un ricorso, presentato a Tribubale Amministrativo Regionale (TAR), ai ai sensi dell'articolo 116 del Codice del processo amministrativo di cui al decreto legislativo 2 luglio 2010, n. 104.<br>
Qualora si tratti di atti delle amministrazioni delle regioni o degli enti locali, il/la richiedente può altresì presentare ricorso al difensore civico competente per ambito territoriale, ove costituito. Qualora tale organo non sia stato istituito, la competenza è attribuita al difensore civico competente per l'ambito territoriale immediatamente superiore.

---

::: {.callout-note}
Questa pagina ha preso molti spunti dai materiali della terza giornata della [Scuola di monitoraggio di Bologna dell’Osservatorio Civico PNRR](https://www.osservatoriocivicopnrr.it/news/27-la-terza-giornata-a-bologna-della-scuola-di-monitoraggio.html).
:::
