---
title: "Il caso dell’Ecuador: la citizen science per la giustizia climatica"
toc: false
---

Un altro caso di rilievo nell’ambito della citizen science è quello che coinvolge le comunità indigene dell’**amazzonia ecuadoriana** supportate da diversi esperti dell’Università di Padova. In questo caso i dati e le informazioni rilevate sono state poi utilizzate anche **in campo legale per provare ad ottenere giustizia ambientale e climatica.**

Ci troviamo in una zona del mondo famosa per il patrimonio forestale e per la ricca biodiversità presente sul territorio. Tuttavia questa caleidoscopica vegetazione ha delle **ferite aperte sanguinanti gravissime.** Una delle tante ferite, tra le più gravi, è legata alla condotta che nei precedenti anni ha avuto Texaco (ora Chevron) nell’Amazzonia ecuadoriana. Nella parte nord dell’Amazzonia ecuadoriana, Texaco ha estratto petrolio per 28 anni senza preoccuparsi degli effetti che tali attività stavano apportando al territorio; così facendo ha fatto profitti, distruggendo e contaminando fiumi, sversando direttamente nel fiume milioni di galloni di acqua contaminata.

Chevron ha abbandonato l’Ecuador nel 1992, eppure la storia recente evidenzia episodi ugualmente infelici, come il caso dell’operato dell’azienda **Petroamazonas.** A Pacayacu dove c’è il campo Petrolero Libertador con all’incirca 120 pozzi petroliferi, sarebbero stati contaminati 10 fiumi, e danneggiate 30 comunità rurali che vivono nel territorio. Secondo uno studio condotto da Acción Ecológica in collaborazione con la Clinica Ambiental di 23 campioni presi nei pozzi d’acqua di uso familiare 22 avevano elevata percentuale di idrocarburi policiclici aromatici. Sempre la stessa impresa ha operato e opera anche all’interno del Parco Nazionale Yasunì, paradiso in miniatura all’interno della paradisiaca foresta amazzonica, designato dall’UNESCO nel 1989 “Riserva della biosfera” per essere una delle regioni con la più alta biodiversità al mondo. Quest’area di 982 mila ettari contiene in un solo ettaro più specie di piante di quante ne contiene tutto il Nord America. Nonostante le premesse, dagli anni ‘70 si è estratto petrolio nel 60% di quello che era il Parco Nazionale. .

Anche in questo caso i**l monitoraggio ambientale ufficiale risulta essere carente e lontano dal descrivere il reale impatto causato dalla presenza dei pozzi petroliferi,** in particolare per quanto riguarda il fenomeno del gas flaring. Oltre al petrolio, infatti, **dai pozzi estraggono anche il gas naturale presente nei giacimenti sotterranei**. Il gas viene poi bruciato *in loco* senza recupero, dati gli elevati costi che comporterebbe il suo trasporto nei luoghi di consumo, producendo delle fiammate (gas flaring).

Gli impatti locali del gas flaring colpiscono sia gli ecosistemi e la biodiversità, sia le comunità locali. **Le uniche informazioni inizialmente disponibili sul gas flaring causato dall’estrazione petrolifera, provenivano da fonti governative** considerate poco oggettive a causa dell’ingerenza dello stato: la maggior parte delle attività estrattive erano ad opera di Petroamazonas, azienda pubblica ecuadoriana.

La necessità di monitorare il fenomeno, ha dato vita ad un progetto portato avanti dall’Università di Padova in collaborazione con le comunità indigene locali, che prevede di rilevare la presenza di gas flaring basandosi sull’analisi delle immagini satellitari notturne per mezzo di un algoritmo chiamato **NIghtfire**. La mappatura realizzata dalle comunità indigene supportate da realtà sociali organizzate e dall'Università di Padova ha rilevato **altri 295 siti di gas flaming rispetto a quelli mappati dal Ministero dell’Ambiente ecuadoriano, 230 dei quali all’interno delle proprietà della compagnia petrolifera statale.**

Il progetto ha inoltre permesso di scoprire la presenza di siti che liberano il gas direttamente nell’atmosfera (gas venting). Si tratta di un fenomeno importante da segnalare a causa dell’impatto climatico che tale procedimento opera.

La mappatura e la conoscenza di questi dati è stata fondamentale per il risvolto legale dell’iniziativa. Inizialmente infatti le comunità nel 2019 hanno avviato una campagna chiamata “Apaguen los mecheros” che aveva l'obiettivo di eliminare il gas flaring legato all’estrazione del petrolio. Successivamente è stata presentata diffida da parte di 9 bambine dell’amazzonia ecuadoriana contro il Ministero dell'energia e delle risorse naturali non rinnovabili e il Ministero dell'ambiente e dell'acqua dell'Ecuador. I**l 26 gennaio 2021 il tribunale di Nueva Loja ha emesso un'ordinanza storica per vietare il gas flaring nell'Amazzonia ecuadoriana.**

In questo senso il progetto di citizen science ha svolto **un ruolo importante in questo processo, consentendo la produzione di informazioni spaziali indipendenti attraverso la mappatura partecipativa con le comunità indigene e contadine.**
